### ISSUE TITLE
Cannot import API

### ISSUE THREAD

**Issue by cosjef** [motiv-labs/janus#121] opened 2017-04-05 22:47 UTC
Cannot import the stub APi at /examples/apis/posts.json. It fails with this response:

HTTP/1.1 400 Bad Request
Content-Length: 27
Content-Type: application/json
Date: Wed, 05 Apr 2017 22:43:03 GMT
Vary: Accept-Encoding

"api definition not found"

**Reproduction Steps:**

1.  Start all docker containers with: docker-compose up -d 
2.  Create valid JWT token
3.  Submit this request from within the janus-master folder via CLI:

http POST 192.168.99.100:8081/apis "Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0OTE0MzM3MTIsImlhdCI6MTQ5MTQzMDExMiwiaWQiOiJhZG1pbiJ9.CfNK3mxh3yArgrDXBLpYArLqPU6PywIDCxBdNEeSQUA" "Content-Type: application/json" < examples/apis/posts.json

**Expected behavior:**

Successful addition of jsonplaceholder API

**Observed behavior:**

API definition not found error.

**Janus version: latest version
**OS and version: Mac OSX 10.11.6

**Comment by italolelis** [comment] 2017-04-06 09:35
Hi @cosjef,

I couldn't reproduce the behavior that you mentioned. What kind of storage for your configs are you using? `File System` or `MongoDB`?

If it is file based you won't be able to use the write operations of the REST API, which means, the API will be in `Read Only` mode. So all changes that you do will be on a file.

If you are using `MongoDB` as your database, then after adding the configuration you MUST restart the gateway so the changes are applied. There is a PR opened #120 which will implement the hot reload feature and you won't have to reload it anymore.

I hope this help you.

**Comment by cosjef** [comment] 2017-04-06 11:52
I am using MongoDB as the storage system. It looks like the gateway does not accept the api definition at all. Are you saying that even in the presence of the error, I should restart the gateway? Do you know what validation in the code is causing this error?

**Comment by italolelis** [comment] 2017-04-06 12:11
Sorry I didn't mean that. 
What I meant is that when it registers the API successfully currently you got to reload the gateway.
I tried to execute here the same request that you've mentioned and it worked....
I've tried on master, maybe there is something wrong with the docker image, I'll try to do the same thing there. 
Just to help me a bit, what version are you using? **2.2.0-rc2**?

**Comment by cosjef** [comment] 2017-04-06 12:52
I was running 2.2.0-rc.1 via direct download from Github master branch. I just downloaded janus-2.2.0-rc.2, unzipped the file and navigated into the directory. Then started the containers with "docker-compose up -d" and all started. Then got a JWT token using this command: http -v --json POST 192.168.99.100:8081/login username=admin password=admin

After obtaining a JWT, I used this command to try adding the API: http -v POST 192.168.99.100:8081/apis "Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0OTE0ODY1NzcsImlhdCI6MTQ5MTQ4Mjk3NywiaWQiOiJhZG1pbiJ9.4h4R6zy_nOemLiRCPDniLxCVxPWzhEwoch5eATqp9V0" "Content-Type: application/json" < examples/apis/posts.json

Same result:
POST /apis HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0OTE0ODY1NzcsImlhdCI6MTQ5MTQ4Mjk3NywiaWQiOiJhZG1pbiJ9.4h4R6zy_nOemLiRCPDniLxCVxPWzhEwoch5eATqp9V0
Connection: keep-alive
Content-Length: 1076
Content-Type: application/json
Host: 192.168.99.100:8081
User-Agent: HTTPie/0.9.8

{
    "active": true,
    "allowed_ips": [],
    "cors_meta": {
        "domains": [
            "*"
        ],
        "enabled": true,
        "exposed_headers": [
            "X-Debug-Token",
            "X-Debug-Token-Link"
        ],
        "methods": [
            "GET",
            "POST",
            "PUT",
            "PATCH",
            "DELETE"
        ],
        "request_headers": [
            "Origin",
            "Authorization",
            "Content-Type"
        ]
    },
    "name": "Posts",
    "oauth_server_name": "local",
    "proxy": {
        "append_path": false,
        "enable_load_balancing": false,
        "hosts": [
            "hellofresh.*"
        ],
        "listen_path": "/posts/*",
        "methods": [
            "GET"
        ],
        "preserve_host": false,
        "strip_path": true,
        "upstream_url": "https://jsonplaceholder.typicode.com/posts"
    },
    "rate_limit": {
        "enabled": true,
        "limit": "10-S"
    },
    "use_basic_auth": false,
    "use_compression": false,
    "use_oauth2": false
}

HTTP/1.1 400 Bad Request
Content-Length: 27
Content-Type: application/json
Date: Thu, 06 Apr 2017 12:49:57 GMT
Vary: Accept-Encoding

"api definition not found"

**Closed as completed** 2017-04-13 14:20 UTC
